// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-nqSio17FSsn-J4QaHzoTHknY842jiwc',
    appId: '1:1086131337009:web:f5adf9b3442f2f1f426210',
    messagingSenderId: '1086131337009',
    projectId: 'studynotes-project',
    authDomain: 'studynotes-project.firebaseapp.com',
    storageBucket: 'studynotes-project.appspot.com',
    measurementId: 'G-EZLDN1VR80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0rwcCjktrfQiq0Yh6_4mWZlsSqM2T18',
    appId: '1:1086131337009:android:cf1fb2d6f83e1126426210',
    messagingSenderId: '1086131337009',
    projectId: 'studynotes-project',
    storageBucket: 'studynotes-project.appspot.com',
  );
}
